library(dplyr)
actlabels<-read.table("activity_labels.txt",col.names=(c("activityid","activity")))
actlabels$activity<-tolower(gsub("_","",actlabels$activity))
names <- scan("features.txt", what=list(NULL,character() ))
names=names[[2]]
dftest<-read.table("X_test.txt",col.names=names,stringsAsFactors=FALSE)
dftestsubj<-as.numeric(readLines("subject_test.txt"))
dftestact<-read.table("y_test.txt",col.names=(c("activityid")))
test<-cbind(dftestsubj,dftestact,dftest)
colnames(test)<-c("subjectid","activityid",names[1:561])
dftrain<-read.table("X_train.txt",col.names=names,stringsAsFactors=FALSE)
dftrainsubj<-as.numeric(readLines("subject_train.txt"))
dftrainact<-read.table("y_train.txt",col.names=(c("activityid")))
train<-cbind(dftrainsubj,dftrainact,dftrain)
colnames(train)<-c("subjectid","activityid",names[1:561])
dffinal<-rbind(test,train)
dffinal<-merge(dffinal,actlabels)
dffinal<-dffinal[ , c(2,564,3:563)]
x<-table(is.na(dffinal))
mc<-grep("\\bmean\\b",names(test))
sc<-grep("\\bstd\\b",names(test))
dffinal<-dffinal[, c(1,2,mc,sc)]
varf<-gsub("[[:punct:]]","",colnames(dffinal))
colnames(dffinal)<- tolower(varf[1:68])
names(dffinal)<-gsub("acc","accelerator",names(dffinal))
names(dffinal)<-gsub("gyro","gyroscope",names(dffinal))
names(dffinal)<-gsub("bodybody","body",names(dffinal))
names(dffinal)<-gsub("mag","magnitude",names(dffinal))
meanandstd<-arrange(dffinal,subjectid,activity)
dfgroupbysubjactivity<-group_by(meanandstd,subjectid,activity)
meanandstdbysubjactivity<-data.frame(summarize_each(dfgroupbysubjactivity,funs(mean(.,na.rm=TRUE)), 3:68))
write.table(meanandstd,file="meanandstd.txt",sep="  ",row.names=False)
write.table(meanandstdbysubjactivity,file="meanandstdbysubjactivity.txt",sep="  ",row.names=False)
